### ISSUE TITLE
Fix the build!

### ISSUE THREAD

**Issue by reinh** [reinh/statsd#73]
It looks like the Travis CI build is failing. We should fix that!

**Comment by raggi** [comment]
I've added a CI on Github actions, with a badge added to the readme.

Unfortunately actions doesn't have readily available builders for anything other than CRuby, so coverage is dropped somewhat.

Next step for fixing this bug should be to add a conditional capability around IPv6 tests, so that we can get Travis green again. We can rely on Github for coverage for the v6 code.

**Comment by reinh** [comment]
A wild @raggi appears! I'm hoping that I can find some time to maintain this gem again this year, FWIW, and thanks again for all of your help.
